// Curated list of well-known cities per US state, used to suggest nearby
// service areas during cook signup. Not exhaustive — just enough well-known
// names per state to give a cook a useful starting point before the platform
// has enough real usage data (via /api/cities) to suggest from instead.
export const US_CITIES_BY_STATE: Record<string, string[]> = {
  'Alabama': ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa'],
  'Alaska': ['Anchorage', 'Fairbanks', 'Juneau'],
  'Arizona': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Gilbert', 'Tempe'],
  'Arkansas': ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale'],
  'California': ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Oakland', 'Fremont', 'Santa Clara', 'Sunnyvale', 'Irvine', 'Long Beach', 'Anaheim'],
  'Colorado': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Boulder'],
  'Connecticut': ['Hartford', 'New Haven', 'Stamford', 'Bridgeport'],
  'Delaware': ['Wilmington', 'Dover', 'Newark'],
  'District of Columbia': ['Washington'],
  'Florida': ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'St. Petersburg', 'Fort Lauderdale'],
  'Georgia': ['Atlanta', 'Augusta', 'Savannah', 'Columbus', 'Alpharetta', 'Sandy Springs'],
  'Hawaii': ['Honolulu', 'Hilo', 'Kailua'],
  'Idaho': ['Boise', 'Meridian', 'Nampa'],
  'Illinois': ['Chicago', 'Naperville', 'Aurora', 'Schaumburg', 'Evanston'],
  'Indiana': ['Indianapolis', 'Fort Wayne', 'Evansville', 'Carmel'],
  'Iowa': ['Des Moines', 'Cedar Rapids', 'Davenport'],
  'Kansas': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'],
  'Kentucky': ['Louisville', 'Lexington', 'Bowling Green'],
  'Louisiana': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
  'Maine': ['Portland', 'Bangor'],
  'Maryland': ['Baltimore', 'Rockville', 'Gaithersburg', 'Silver Spring', 'Bethesda'],
  'Massachusetts': ['Boston', 'Cambridge', 'Worcester', 'Somerville', 'Lowell'],
  'Michigan': ['Detroit', 'Ann Arbor', 'Grand Rapids', 'Troy', 'Novi'],
  'Minnesota': ['Minneapolis', 'St. Paul', 'Bloomington', 'Eden Prairie'],
  'Mississippi': ['Jackson', 'Gulfport', 'Southaven'],
  'Missouri': ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'],
  'Montana': ['Billings', 'Missoula', 'Bozeman'],
  'Nebraska': ['Omaha', 'Lincoln'],
  'Nevada': ['Las Vegas', 'Henderson', 'Reno'],
  'New Hampshire': ['Manchester', 'Nashua'],
  'New Jersey': ['Newark', 'Jersey City', 'Edison', 'Princeton', 'Woodbridge'],
  'New Mexico': ['Albuquerque', 'Santa Fe', 'Las Cruces'],
  'New York': ['New York City', 'Buffalo', 'Rochester', 'Syracuse', 'Albany', 'Yonkers'],
  'North Carolina': ['Charlotte', 'Raleigh', 'Durham', 'Cary', 'Greensboro'],
  'North Dakota': ['Fargo', 'Bismarck'],
  'Ohio': ['Columbus', 'Cleveland', 'Cincinnati', 'Dayton', 'Dublin'],
  'Oklahoma': ['Oklahoma City', 'Tulsa', 'Norman'],
  'Oregon': ['Portland', 'Eugene', 'Salem', 'Beaverton', 'Hillsboro'],
  'Pennsylvania': ['Philadelphia', 'Pittsburgh', 'Allentown', 'King of Prussia'],
  'Rhode Island': ['Providence', 'Warwick'],
  'South Carolina': ['Columbia', 'Charleston', 'Greenville'],
  'South Dakota': ['Sioux Falls', 'Rapid City'],
  'Tennessee': ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'],
  'Texas': ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'Plano', 'Irving', 'Frisco', 'Sugar Land'],
  'Utah': ['Salt Lake City', 'Provo', 'West Valley City'],
  'Vermont': ['Burlington', 'Montpelier'],
  'Virginia': ['Richmond', 'Virginia Beach', 'Arlington', 'Alexandria', 'Fairfax'],
  'Washington': ['Seattle', 'Bellevue', 'Redmond', 'Tacoma', 'Spokane', 'Renton'],
  'West Virginia': ['Charleston', 'Huntington'],
  'Wisconsin': ['Milwaukee', 'Madison', 'Green Bay'],
  'Wyoming': ['Cheyenne', 'Casper'],
}
